#!/bin/bash

. "myfunction.spec"


sed -e "s|@FUNCTION_NAME@|${FUNCTION_NAME}|g" \
    -e "s|@CONSTANT_LIST_ARG@|${CONSTANT_LIST_ARG}|g" \
    -e "s|@CONSTANT_LIST@|${CONSTANT_LIST}|g" \
    -e "s|@FUNCTION_INPUT@|${FUNCTION_INPUT}|g" \
    -e "s|@FUNCTION_OUTPUT@|${FUNCTION_OUTPUT}|g" \
    -e "s|@FUNCTION_TITLE@|${FUNCTION_TITLE}|g" \
    -e "s|@CONSTANT_LIST_INITIALIZATION_LIST@|${CONSTANT_LIST_INITIALIZATION_LIST}|g" \
    -e "s|@VARIABLE_RENAMING@|${VARIABLE_RENAMING}|g" \
    -e "s|@RESULT@|${RESULT}|g" \
    -e "s|@GRADIENT_CASES@|${GRADIENT_CASES}|g" \
    function.cc.in > function.cc.out
